name: Waka Readme

on:
  schedule:
    # Runs at 12 AM IST (6:30 PM UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_EDITORS: false
          SYMBOL_VERSION: 2
          
