name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          SHOW_TOTAL_CODE_TIME: True
          SHOW_COMMIT: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_LINES_OF_CODE: True
          SHOW_OS: False
          SHOW_PROJECTS: False
          SYMBOL_VERSION: 3
          DEBUG_LOGGING: False
          UPDATED_DATE_FORMAT: "%d-%m-%Y %H:%M"
